spring:
  application:
    name: ConnectSphere

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/connect_sphere
    username: manish
    password: Manish7200

  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8082
